import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import { AAR_SECTIONS, type FormData } from "@/lib/constants";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: "#1a1a1a",
  },
  header: {
    borderBottomWidth: 2,
    borderBottomColor: "#dc2626",
    paddingBottom: 12,
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    color: "#1a1a1a",
  },
  headerSubtitle: {
    fontSize: 10,
    color: "#666666",
    marginTop: 4,
  },
  missionDetails: {
    backgroundColor: "#f8f8f8",
    padding: 12,
    borderRadius: 4,
    marginBottom: 20,
  },
  missionRow: {
    flexDirection: "row",
    marginBottom: 4,
  },
  missionLabel: {
    fontFamily: "Helvetica-Bold",
    width: 120,
    color: "#444444",
  },
  missionValue: {
    flex: 1,
  },
  sectionContainer: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    color: "#dc2626",
    marginBottom: 6,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e5e5",
  },
  sectionBody: {
    fontSize: 11,
    lineHeight: 1.5,
    color: "#333333",
  },
  noContent: {
    fontSize: 11,
    color: "#999999",
    fontStyle: "italic",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    borderTopWidth: 1,
    borderTopColor: "#e5e5e5",
    paddingTop: 8,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  footerText: {
    fontSize: 8,
    color: "#999999",
  },
});

function formatDate(dateStr: string): string {
  if (!dateStr) return "";
  const [y, m, d] = dateStr.split("-");
  return `${m}/${d}/${y}`;
}

interface PDFReportProps {
  data: FormData;
}

export function PDFReport({ data }: PDFReportProps) {
  const timestamp = new Date().toLocaleString("en-US", {
    timeZone: "Pacific/Honolulu",
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  });

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.headerTitle}>
            Rescue 10 Helicopter Ops — After Action Review
          </Text>
          <Text style={styles.headerSubtitle}>
            Maui County Fire Department — Helicopter Operations
          </Text>
        </View>

        {/* Mission Details */}
        <View style={styles.missionDetails}>
          <View style={styles.missionRow}>
            <Text style={styles.missionLabel}>Date of Mission:</Text>
            <Text style={styles.missionValue}>{formatDate(data.date)}</Text>
          </View>
          <View style={styles.missionRow}>
            <Text style={styles.missionLabel}>Pilot:</Text>
            <Text style={styles.missionValue}>{data.pilotName}</Text>
          </View>
          <View style={styles.missionRow}>
            <Text style={styles.missionLabel}>Hoist Operator:</Text>
            <Text style={styles.missionValue}>{data.hoistOperator}</Text>
          </View>
          {data.crewMembers && (
            <View style={styles.missionRow}>
              <Text style={styles.missionLabel}>Crew Members:</Text>
              <Text style={styles.missionValue}>{data.crewMembers}</Text>
            </View>
          )}
        </View>

        {/* Sections */}
        {AAR_SECTIONS.map((section, i) => (
          <View key={section.id} style={styles.sectionContainer} wrap={false}>
            <Text style={styles.sectionTitle}>
              {section.icon} {i + 1}. {section.title}
            </Text>
            {data.sections[section.id] ? (
              <Text style={styles.sectionBody}>
                {data.sections[section.id]}
              </Text>
            ) : (
              <Text style={styles.noContent}>No notes provided.</Text>
            )}
          </View>
        ))}

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>
            Generated by Rescue 10 AAR System
          </Text>
          <Text style={styles.footerText}>{timestamp}</Text>
        </View>
      </Page>
    </Document>
  );
}
